apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: saude-poc
  labels: { app: patient-service }
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector: { app: patient-service }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: saude-poc
  labels: { app: patient-service }
spec:
  replicas: 2          # RNF-02
  selector:
    matchLabels: { app: patient-service }
  template:
    metadata:
      labels: { app: patient-service, version: v1 }
    spec:
      containers:
        - name: patient-service
          image: saude-publica-poc-patient-service:latest
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8081 }]
          env:
            - { name: SPRING_DATASOURCE_URL, value: "jdbc:postgresql://postgres:5432/patientdb" }
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom: { configMapKeyRef: { name: shared-config, key: POSTGRES_USER } }
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom: { secretKeyRef: { name: shared-secrets, key: POSTGRES_PASSWORD } }
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: 8081 }
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: 8081 }
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            requests: { cpu: "250m", memory: "512Mi" }
            limits:   { cpu: "1000m", memory: "1Gi" }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: patient-service
  namespace: saude-poc
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: patient-service }
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 70 }   # RNF-01
